alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gpl='git pull'
alias gps='git push'
alias gr='git rev-parse --short HEAD'
alias gs='git status'
alias gwd='git diff --word-diff=color'
alias gwdc='git diff --word-diff=color --cached'
alias mr='ls -1rt | tail -n 1'
alias mrd='ls -1rtd */ | tail -n 1'
alias ta='tmux a -t'
alias tls='tmux ls'
