alias f='find . -iname'
alias g=grep
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gcm='git commit -m'
alias gco='git checkout --recurse-submodules'
alias gcp='git cherry-pick'
alias gpl='git pull'
alias gps='git push'
alias gr='git rev-parse --short HEAD'
alias gs='git status'
alias gwd='git diff --word-diff=color'
alias gwdc='git diff --word-diff=color --cached'
alias p8='ping 8.8.8.8'
